# Generated by Django 3.2.12 on 2022-02-03 00:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': '同一のユーザー名が既に登録されています'}, max_length=100, unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(error_messages={'unique': '同一のメールアドレスが既に登録されています'}, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('name_kana', models.CharField(max_length=60, verbose_name='名前(ふりがな)')),
                ('join_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理者')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
