# Generated by Django 3.2.12 on 2022-02-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCreation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='CommentCreation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('username', models.CharField(default='匿名', max_length=30, verbose_name='ユーザー名')),
                ('topic', models.CharField(max_length=100, verbose_name='タイトル')),
                ('comment', models.CharField(max_length=2000, verbose_name='内容')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.categorycreation', verbose_name='カテゴリー')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='投稿ユーザ')),
            ],
        ),
    ]
